---
title: "Research"
---

```{=html}
<style>
p.small {
    line-height: 0.5;
}
.abstract {
  display: none;
  padding: 15px 25px;
  margin: 0 5px 10px 5px;
  background-color: #EEE;
}

div .p {
    padding: 5px 0 10px 0;

}
.cl{
    font-weight: bolder;
}

.place_holder {
    height: 10px;
}
</style>
```
```{=html}
<script src="https://code.jquery.com/jquery-latest.min.js"
        type="text/javascript"></script>
```
```{=html}
<script>
$(document).ready(function(){
  $(document).on('touchstart click','.cl', function(){
    $(this).parent().children(".abstract").toggle();
  });
});
</script>
```

------------------------------------------------------------------------

------------------------------------------------------------------------

## Peer-reviewed publications

<ol reversed>



<li>  [**"The Unexpected Consequences of the COVID-19 Pandemic on Maritime Crime: Evidence from Indonesia and Nigeria"**](https://doi.org/10.1177/22338659221151130) *International Area Studies Review* (2023).


<!-- [<a class='cl'>Abstract</a>] -->

<!--     <p class="abstract"> -->

<!-- The economic fallout from the COVID-19 pandemic has been devastating. Job losses, negative growth rates, and increased poverty have all followed rising infection rates. The economic costs have been especially challenging for many piracy-prone countries. The international monetary fund anticipates sizable unemployment increases in many Indo-Pacific countries. Deeper and more durable economic damage may materialize in some West African countries. Often, negative economic shocks produce surges in crime, both on land and at sea. The present study evaluates the effects of COVID-19 on maritime pirate attacks in two countries, Nigeria, located in the Gulf of Guinea, and Indonesia, located in the Indo-Pacific. We employ monthly and quarterly data on government measures to prevent infection, sea-piracy incidents, and economic conditions to explore whether the subsequent economic fallout produced more maritime crime. We do not find clear evidence of this relationship in Indonesia. However, COVID-19-induced stringency measure does appear to have increased sea-piracy incidents in Nigeria. -->

<!--     </p> <p> </p> -->

<li> [**"Should I Signal Trust? Effect of Terrorism on Interpersonal Trust in Post-conflict and Non-post-conflict Countries"**](https://doi.org/10.1080/09546553.2022.2075265) *Terrorism and Political Violence* (2022).

<!-- [<a class='cl'>Abstract</a>] -->

<!--     <p class="abstract"> -->

<!-- Generalized interpersonal trust is an essential component of a functioning society. While some studies have examined how the perception of terrorism affects trust, cross-national works investigating the impact of actual terrorist attacks on individual trust remain mixed. In this paper, I use insights from existing studies to disaggregate generalized interpersonal trust in response to terrorism in two distinct dimensions, prosocial motivation, and strategic signaling. While threat perception from terrorism lowers interpersonal trust in all contexts,  I argue that actual events distinctively shape a person's interpersonal trust. In a relatively stable and secure context of a non-post-conflict country, individuals living closer to terrorist incidents express increased interpersonal trust. But in post-conflict countries, those closer to terrorist incidents tend to show more distrust. To test the argument, I use the World Values Survey dataset of  52 states and create a terrorism scale for 717 survey regions within the countries, considering their spatial and temporal closeness to each terrorist incident. Results obtained from three-level hierarchical models (state, region, and individual) are robust and contribute to our understanding of how terrorism shapes interpersonal trust in different contexts. -->

<!--     </p> <p> </p> -->

<li> [**"Interstate Hostility and Maritime Crime: Evidence from South East Asia"**](https://doi.org/10.1016/j.marpol.2022.105134) (with Aaron Gold & B. Prins). *Marine Policy* (2021). <!-- [<a class='cl'>Abstract</a>]    <p class="abstract"> --> <!-- Maritime Asia remains crucial to global economic growth and prosperity. Nearly 40% of the world's seaborne trade transits the South China Sea each year, and nine of the top ten busiest container ports in the world are located in the Indo-Pacific region. But uncertainties also pervade the region as governments struggle to combat numerous security challenges while violent non-state actors and trans-border criminal groups continue to exploit the environment.  In this study, we examine the nexus between maritime crime and inter-state security, centering on the tactical decision-making of non-state criminal actors. To avoid capture, maritime criminals locate their illicit activities near sea-boundaries where rival states aim to avoid regime confrontations that could escalate to more costly disputes. Pirates, smugglers, and illegal fishers can use these contested border zones as sanctuaries similar to guerilla forces fleeing across land boundaries to avoid pitched battles with regime military units. Using an original geocoded dataset on maritime piracy (MPELD), we find significant support for our hypothesis that conflict among states substantively influences the location of maritime crime. Our study has important implications for global efforts to counter transnational criminal organizations and their illicit activities in maritime spaces defined by territorial quarrels. --> <!--     </p> <p> </p> -->

<li> [**"Deploying to protect: the effect of military peacekeeping deployments on violence against civilians"**](https://doi.org/10.1080/13533312.2019.1660166) (with B. Prins). *International Peacekeeping* (2020).

<!-- [<a class='cl'>Abstract</a>] -->

<!--     <p class="abstract"> -->

<!-- Do UN peacekeeping forces protect civilians from harm in post-war environments? Current evidence suggests that the answer to this question is yes. But extant research mostly examines this relationship at the country-level and consequently has logical difficulty tracing decreases in civilian fatalities to actual peacekeeper activities. We would have more confidence in the ability of peacekeepers to limit harm and protect non-combatants if the reduction in violence occurred locally where blue helmets were positioned. Using original geocoded data of yearly UN deployments in four Sub-Saharan African conflicts (Sudan, South Sudan, Democratic Republic of Congo, and Ivory Coast), we find that peacekeeping units get locally deployed to violent post-war areas and they reduce the level of civilian harm almost immediately. But, in areas without violent clashes between government forces and rebels, we find peacekeeping units more responsive to civilian targeting by rebels, which indicates a reluctance among peacekeepers to confront government forces that target civilians. While host nation consent is crucial for the success of a peacekeeping mission, the findings from this study caution against nurturing illiberal regimes by failing to check government atrocities. The failure to confront government abuse can jeopardize long-term peace and reconciliation. -->

<!--     </p> <p> </p> -->

<li> [**"UN Troop Deployment and Preventing Violence Against Civilians in Darfur"**](https://doi.org/10.1080/03050629.2019.1593161). *International Interactions* (2019).

<!-- [<a class='cl'>Abstract</a>] -->

<!--     <p class="abstract"> -->

<!-- Does the presence of UN peacekeeping force lower civilian fatalities at the local level? If it does, is it because of their coercive military capacity or for other reasons such as their roles in monitoring and reporting violent atrocities? To explore these questions, I study the deployment of peacekeeping units in Darfur and its impact on violence against civilians. Using original geocoded data of UN deployments before and after the intervention, I examine what aspects of such deployments impact one-sided civilian killings by government and rebel groups. Results indicate that deploying UN peacekeepers in an area restrains belligerent from targeting civilians. However, the military capacity of peacekeepers is not a significant predictor of violence against civilians. While their ability to defend themselves is extremely important for peacekeepers, these findings caution against the militarization trend in UN peacekeeping and seek to reshift focus on other substantive aspects of peacekeeping. -->

<!--     </p> <p> </p>  -->

<li> [**"Fueling rebellion: Maritime piracy and the duration of civil war"**](https://doi.org/10.1177/2233865919833975) (with B. Prins & U. Daxecker). *International Area Studies Review* (2019).

<!-- [<a class='cl'>Abstract</a>] -->

<!--     <p class="abstract"> -->

<!-- Extant research shows that the presence of natural resources can prolong civil wars. But research also indicates that as rebel groups become stronger, conflicts tend to shorten. These studies suggest an unclear association among the three variables—resources, rebel strength, and conflict duration. If resources increase the fighting ability of rebels, then why do they not shorten conflicts? To understand this relationship, we examine incidents of maritime piracy, which unlike other resources are more clearly exploited by rebel groups rather than states and offer new insight on how this might affect the persistence of civil war. The findings suggest that the use of piracy by weaker rebel groups shortens conflict but prolongs it when exploited by stronger rebel groups. We think our conditional analyses allow us to discern insurgencies driven at least in part by greedy rebels and therefore better illuminate the causal process by which resource wealth prolongs civil war. -->

<!--     </p> <p> </p> -->

<li> [**"Who Wins, Who Loses, Who Negotiates Peace in Civil Wars: Does Regime Type Matter?"**](https://doi.org/10.1093/jogss/ogz011) (with T.D. Mason & M. Gurses). *Journal of Global Security Studies* (2019).

<!-- [<a class='cl'>Abstract</a>] -->

<!--     <p class="abstract"> -->

<!-- Previous research has shown that the outcome of a civil war is related to conflict duration: military victory by either the government or the rebels occurs early if it occurs at all, and the longer a civil war lasts, the more likely it is to end in a negotiated settlement. The models of civil war duration and outcome that have produced these findings are built on characteristics of the civil war and less on attributes of the state itself, other than where the state lies on the Polity autocracy-democracy scale. We propose that how civil wars end varies not only between democracies and authoritarian regimes but among the different authoritarian regime types identified by Geddes, Wright, and Franz. The distinguishing attributes of these regime types—democracy, one-party, personalist, military, monarchical—should lead to different likelihood in defeating a rebel movement, being defeated by a rebel movement, and negotiating a peace agreement with a rebel movement. Results from a series of competing-risk models using the Uppsala–Peace Research Institute Oslo Armed Conflict Dataset demonstrate support for our claim that how civil wars end is partly a function of the characteristics of the regime. -->

<!--     </p> <p> </p> -->

<li>  [**"What makes an ex-combatant happy? A micro-analysis of disarmament, demobilization, and reintegration in South Sudan"**](https://doi.org/10.1111/isqu.12186) (with P. Khadka & C. L. Thyne). *International Studies Quarterly* (2015).

<!-- [<a class='cl'>Abstract</a>] -->

<!--     <p class="abstract"> -->

<!-- Successful management of combatants through disarmament, demobilization, and reintegration (DDR) remains one of the main challenges of post-conflict peacebuilding. While DDR is meant to contribute to a secure post-conflict environment conducive to economic and political development, the success of DDR efforts remains mixed. Unlike previous work focusing on procedural aspects or post-conflict reconstruction and development, we shift the focus to understand microlevel conditions—economic, security, and ethnic concerns—that influence ex-combatants' satisfaction with DDR. We argue that ex-combatant satisfaction with DDR should increase as individual-level economic conditions increase, as security situations improve, and as ethnic tensions decrease. We test our expectations using an original data set collected with field interviews and surveys from 122 ex-combatants in South Sudan in 2011–2012. We find that participants are more satisfied when their income-generating activity is based on DDR job training and when the UN has a large presence in their area. Concerns about political instability and an abundance of firearms make ex-combatants less satisfied with DDR. -->

<!--     </p> <p> </p> -->

<li> [**"Cost of violence and the peaceful way out: A comparison of the Provisional Irish Republican Army and the Communist Party of Nepal (Maoists)"**](https://doi.org/10.1080/17467586.2011.575170). *Dynamics of Asymmetric Conflict* (2011). [Download](https://www.researchgate.net/profile/Anup_Phayal/publication/233070516_Cost_of_violence_and_the_peaceful_way_out_A_comparison_of_the_Provisional_Irish_Republican_Army_and_the_Communist_Party_of_Nepal_Maoists/links/5c71f8dea6fdcc471595ff3f/Cost-of-violence-and-the-peaceful-way-out-A-comparison-of-the-Provisional-Irish-Republican-Army-and-the-Communist-Party-of-Nepal-Maoists.pdf)

<!--  [<a class='cl'>Abstract</a>] -->

<!--     <p class="abstract"> -->

<!-- One of the ways to end protracted, violent, intrastate conflict is negotiated settlement where the rebel parties negotiate with the government and give up armed struggle. However, the most intriguing puzzle is: what influences the rebels to come to the negotiating table and opt for peace? The Communist Party of Nepal (Maoists) and the Provisional Irish Republican Army (PIRA) are recent examples of rebel groups that have renounced violence and transformed into mainstream political parties after waging insurgency for many years. These two cases present an opportunity to analyze factors that lead rebel parties to renounce violence. In this article, I argue that violent rebel groups settle for peaceful means owing to their perception of the high cost of violence that arises from pressures exerted by the military means of a state, by domestic groups, and by the international community. In both cases, when the state opened up political space to accommodate the rebel group, accumulated pressures influenced them to renounce violence. The study indicates how civil society, with solidarity from the global community, is able to defy the mobilization narrative of a rebel group and pressure them to renounce violence. -->

<!--     </p> <p> </p> -->

</ol>

------------------------------------------------------------------------

```{=html}
<!--- ## Work in progress

* [**"Terrorism and trust"**](../files/research_folder/Full manuscript_terrorism and trust.pdf)

* [**"Community driven conflict resolution: Evidence from a RCT in Ivory Coast"**](../files/research_folder/Khadka and Phayal CDCR apsa sept 2020.pdf) (with Prabin Khadka)

* [**"Terrorist targetting"**](with Sambuddha Ghatak & Brandon Prins) --->
```
## Non-Peer-reviewed

<ol reversed>



<li> [Tackling maritime security requires a revised Indo-Pacific strategy.](https://warontherocks.com/2023/06/tackling-maritime-security-requires-a-revised-indo-pacific-strategy/) War on the Rocks, June 2023.

<li>  [What will Keep ships and people Safer in the Gulf of Guinea.](https://www.washingtonpost.com/politics/2022/06/09/gulf-of-guinea-piracy/) Monkey cage, The Washington Post, June 2022.

<li> [Fights over marine boundaries are creating safe zones for pirates.](https://www.washingtonpost.com/politics/2021/08/05/fights-over-marine-boundaries-are-creating-safe-zones-pirates/) Monkey cage, The Washington Post, August 2021.

<li> [Force vs Legitimacy: UN Peacekeeping and protecting civilian lives.](https://politicalviolenceataglance.org/2019/04/22/force-vs-legitimacy-un-peacekeeping-and-protecting-civilian-lives/#respond) Political Violence At a Glance, April 2019

<li> [Satisfaction among ex-combatants after DDR.](https://politicalviolenceataglance.org/2016/05/30/satisfaction-among-ex-combatants-after-ddr/) Political Violence At a Glance, May 2016

</ol>
